// Canonical ESLint flat config (see STACK.md). `./.nuxt/eslint.config.mjs` is
// generated by `nuxt prepare` at the engine root (the lint script runs it
// first). eslint-config-prettier is appended LAST so any stylistic rule that
// would fight Prettier is disabled — Prettier owns formatting, ESLint owns
// correctness. Consuming game repos replicate this file verbatim against their
// own generated config.
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
  // Verification scripts drive a real browser; code inside page.evaluate()
  // callbacks executes in the page, so browser globals are legitimate there.
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        document: 'readonly',
        getComputedStyle: 'readonly',
      },
    },
  },
  // The fixtures dev-app builds into its own ignored dirs.
  {
    ignores: ['fixtures/.nuxt/**', 'fixtures/.vercel/**', 'fixtures/node_modules/**'],
  },
  eslintConfigPrettier,
);
